name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Quick tests run
        run: dotnet test --configuration Release --no-restore

      - name: Publish Windows x64
        run: dotnet publish src/2048Game/2048Game.csproj --configuration Release --no-restore --output ./output/win-x64 --self-contained --runtime win-x64

      - name: Publish Linux x64
        run: dotnet publish src/2048Game/2048Game.csproj --configuration Release --no-restore --output ./output/linux-x64 --self-contained --runtime linux-x64

      - name: Publish macOS x64
        run: dotnet publish src/2048Game/2048Game.csproj --configuration Release --no-restore --output ./output/osx-x64 --self-contained --runtime osx-x64

      - name: Create release artifact (zip)
        run: |
          zip -r 2048Game-win-x64.zip ./output/win-x64
          zip -r 2048Game-linux-x64.zip ./output/linux-x64
          zip -r 2048Game-osx-x64.zip ./output/osx-x64

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./2048Game-win-x64.zip
            ./2048Game-linux-x64.zip
            ./2048Game-osx-x64.zip
          tag_name: ${{github.event.release.tag_name}}
          name: Release ${{github.event.release.tag_name}}
          body: ${{ github.event.release.body }}
